### ISSUE TITLE
Its not working.

### ISSUE THREAD

**Issue by php7webmob** [CodeDrips/gatsby-plugin-tidio#2]
How can I debug what is wrong in local env.

**Comment by garethpbk** [comment]
Yeah not working here either, in development or production. Looking at its directory in node_modules, it looks like the gatsby-ssr.js file isn't properly transpiled? it's in the src directory but not the base directory where it should be.

Gonna roll my own tidio plugin I guess.

**Comment by eulo** [comment]
Resolved in version 1.0.3
